#!/usr/bin/env bash
set -euo pipefail

# ---------------------------------------------------------------------------
# Resolve paths (follow symlink to real location)
# ---------------------------------------------------------------------------
_SELF="${BASH_SOURCE[0]}"
while [[ -L "$_SELF" ]]; do
    _DIR="$(cd "$(dirname "$_SELF")" && pwd)"
    _SELF="$(readlink "$_SELF")"
    [[ "$_SELF" != /* ]] && _SELF="$_DIR/$_SELF"
done
SCRIPT_DIR="$(cd "$(dirname "$_SELF")" && pwd)"
AZ_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
export AZ_DIR

# ---------------------------------------------------------------------------
# Source libraries
# ---------------------------------------------------------------------------
source "$AZ_DIR/lib/common.sh"
az_init

for _lib in detect tuning nginx php mariadb redis wordpress ssl firewall security cron backup; do
    [[ -f "$AZ_DIR/lib/${_lib}.sh" ]] && source "$AZ_DIR/lib/${_lib}.sh"
done

trap 'trap_error $LINENO "$BASH_COMMAND"' ERR

# ---------------------------------------------------------------------------
# Load state
# ---------------------------------------------------------------------------
load_state() {
    [[ ! -f "$AZ_STATE_FILE" ]] && die "az-wp not installed. Run install.sh first."
    DOMAIN="$(state_get DOMAIN)" || die "DOMAIN not found in state."
    PHP_VERSION="$(state_get PHP_VERSION 2>/dev/null)" || PHP_VERSION="8.5"
    SITE_USER="$(state_get SITE_USER 2>/dev/null)"     || SITE_USER=""
    WEB_ROOT="$(state_get WEB_ROOT 2>/dev/null)"       || WEB_ROOT=""
    CACHE_PATH="$(state_get CACHE_PATH 2>/dev/null)"   || CACHE_PATH=""
    REDIS_SOCK="$(state_get REDIS_SOCK 2>/dev/null)"   || REDIS_SOCK="/run/redis/redis-server.sock"
    DB_NAME="$(state_get DB_NAME 2>/dev/null)"         || DB_NAME=""
    DB_USER="$(state_get DB_USER 2>/dev/null)"         || DB_USER=""
    DB_PASS="$(state_get DB_PASS 2>/dev/null)"         || DB_PASS=""
}

# ---------------------------------------------------------------------------
# WP-CLI helper (suppresses PHP 8.5 deprecation noise)
# ---------------------------------------------------------------------------
wp_run() {
    sudo -u "$SITE_USER" wp "$@" --path="$WEB_ROOT" 2>&1 | grep -v "^Deprecated:" || true
}

# ---------------------------------------------------------------------------
# Section header helper
# ---------------------------------------------------------------------------
_header() { printf "\n${BOLD}  %s${NC}\n  ──────────────────────────────────────\n" "$1"; }

# Auto-login: generate one-time token URL for admin user
_wp_auto_login() {
    local token
    token="$(openssl rand -hex 32)"
    local expiry
    expiry="$(date -d '+1 hour' '+%s' 2>/dev/null || date -v+1H '+%s' 2>/dev/null)"

    # Store token in WP option (WP-CLI)
    wp_run option update _az_wp_login_token "${token}:${expiry}" > /dev/null

    # Ensure mu-plugin exists for token processing
    local mu_dir="$WEB_ROOT/wp-content/mu-plugins"
    local mu_file="$mu_dir/az-wp-autologin.php"
    if [[ ! -f "$mu_file" ]]; then
        mkdir -p "$mu_dir"
        cat > "$mu_file" <<'MUPHP'
<?php
/**
 * az-wp Auto-Login via Token
 * Handles one-time login tokens generated by az-wp CLI.
 */
add_action('init', function () {
    if (empty($_GET['az_login_token'])) return;
    $token = sanitize_text_field($_GET['az_login_token']);
    $stored = get_option('_az_wp_login_token', '');
    if (empty($stored)) return;

    list($valid_token, $expiry) = explode(':', $stored, 2);
    if (!hash_equals($valid_token, $token)) return;
    if (time() > (int)$expiry) {
        delete_option('_az_wp_login_token');
        wp_die('Login link expired. Generate a new one: az-wp login');
    }

    // Valid — login as user ID 1 and delete token (one-time use)
    delete_option('_az_wp_login_token');
    wp_set_auth_cookie(1, true);
    wp_set_current_user(1);
    wp_safe_redirect(admin_url());
    exit;
}, 1);
MUPHP
        chown "$SITE_USER:$SITE_USER" "$mu_file"
    fi

    local login_url="https://${DOMAIN}/?az_login_token=${token}"
    printf "\n  ${BOLD}Auto-Login URL:${NC}\n"
    printf "  %s\n\n" "$login_url"
    printf "  ${DIM}One-time use. Expires in 1 hour.${NC}\n"
    printf "  ${DIM}Generate new: az-wp login${NC}\n\n"
}

# Generate/refresh cache-stats.json with real file count and size
_refresh_cache_stats() {
    local stats_dir="/home/${SITE_USER}/cache"
    local stats_file="${stats_dir}/cache-stats.json"
    local cache_dir="${CACHE_PATH:-${stats_dir}/fastcgi}"
    mkdir -p "$stats_dir"
    local count size
    count="$(find "$cache_dir" -type f 2>/dev/null | wc -l || echo 0)"
    size="$(du -sb "$cache_dir" 2>/dev/null | awk '{print $1}' || echo 0)"
    printf '{"files":%s,"size":%s,"updated":"%s"}' "$count" "$size" "$(date '+%Y-%m-%d %H:%M:%S')" > "$stats_file"
    chown "${SITE_USER}:${SITE_USER}" "$stats_file" 2>/dev/null || true
}


# ===========================================================================
# MAIN MENU
# ===========================================================================
show_menu() {
    printf "\n${CYAN}===================================================${NC}\n"
    printf "${BOLD}  az-wp — WordPress Management v%s${NC}\n" "$AZ_VERSION"
    printf "  Site: ${GREEN}%s${NC}\n" "$DOMAIN"
    printf "${CYAN}===================================================${NC}\n\n"
    printf "  1) Status        System + services overview\n"
    printf "  2) WordPress     Update, plugins, debug, maintenance\n"
    printf "  3) Database      phpMyAdmin, optimize, credentials\n"
    printf "  4) Cache         Purge FastCGI + Redis\n"
    printf "  5) Backup        Full backup, restore, schedule\n"
    printf "  6) Cron          Manage cron jobs\n"
    printf "  7) Domain        Change domain\n"
    printf "  8) Advanced      SSL, security, performance, workers\n"
    printf "  9) Help          Commands reference\n"
    printf "\n  0) Exit\n"
}

show_usage() {
    cat <<'EOF'
Usage: az-wp [command] [subcommand]

── Quick Actions ──────────────────────────────────
  az-wp status              System dashboard
  az-wp login               Auto-login URL (one-time, 1h expiry)
  az-wp cache purge         Purge all caches (FastCGI + Redis)
  az-wp db pma              Open phpMyAdmin (auto-login URL)
  az-wp backup full         Full backup (files + DB)

── WordPress ──────────────────────────────────────
  az-wp wp update           Update core + plugins + themes
  az-wp wp plugins          List installed plugins
  az-wp wp debug on|off     Toggle debug mode
  az-wp wp maintenance      Toggle maintenance mode
  az-wp wp admin-pass       Reset admin password
  az-wp wp search-replace   Search & replace in database
  az-wp wp cli              WP-CLI interactive shell

── Database ───────────────────────────────────────
  az-wp db pma              phpMyAdmin login URL (24h expiry)
  az-wp db info             Show DB credentials + paths
  az-wp db optimize         Optimize database tables
  az-wp db cli              MySQL CLI prompt

── Cache ──────────────────────────────────────────
  az-wp cache purge         Purge FastCGI + Redis
  az-wp cache purge-fcgi    Purge FastCGI only
  az-wp cache purge-redis   Purge Redis only
  az-wp cache stats         Cache size + hit stats

── Backup ─────────────────────────────────────────
  az-wp backup full         Full backup (files + DB)
  az-wp backup list         List available backups
  az-wp backup restore FILE Restore from backup
  az-wp backup schedule     Configure auto backup schedule

── Cron ───────────────────────────────────────────
  az-wp cron list           List all cron jobs
  az-wp cron add            Add cron (paste full line)
  az-wp cron preset         Install AffiliateCMS cron preset
  az-wp cron remove NAME    Remove a cron job
  az-wp cron remove-all     Remove all custom crons

── Domain ─────────────────────────────────────────
  az-wp domain change       Change site domain (DB + nginx + SSL)

── Advanced ───────────────────────────────────────
  az-wp advanced ssl        SSL: issue, renew, info
  az-wp advanced security   Fail2Ban status, unban IP, UFW
  az-wp advanced perf       Performance: retune, TTFB, FPM, OPcache
  az-wp advanced services   Restart/reload services
  az-wp advanced workers    FPM pool status, kill stuck
  az-wp advanced pma-config phpMyAdmin: enable, disable, regenerate
  az-wp retune              Shortcut: re-tune after VPS resize

── Other ──────────────────────────────────────────
  az-wp help                This help page
  az-wp                     Interactive menu
EOF
}

# ===========================================================================
# 1) STATUS
# ===========================================================================
menu_status() {
    _header "System Status"

    local up; up="$(uptime -p 2>/dev/null | sed 's/^up //')" || up="unknown"
    printf "  Uptime:     %s\n" "$up"

    local load; load="$(awk '{print $1, $2, $3}' /proc/loadavg 2>/dev/null)" || load="unknown"
    printf "  Load:       %s\n" "$load"

    local ram_total ram_used ram_pct
    ram_total="$(free -m | awk '/^Mem:/ {print $2}')"
    ram_used="$(free -m | awk '/^Mem:/ {print $3}')"
    ram_pct=$(( ram_total > 0 ? ram_used * 100 / ram_total : 0 ))
    printf "  RAM:        %sMB / %sMB (%s%%)\n" "$ram_used" "$ram_total" "$ram_pct"

    local disk_info; disk_info="$(df -h / | awk 'NR==2 {printf "%s / %s (%s)", $3, $2, $5}')" || disk_info="unknown"
    printf "  Disk:       %s\n" "$disk_info"

    printf "\n  ${BOLD}Services:${NC}\n"
    local svc svc_status
    for svc in nginx "php${PHP_VERSION}-fpm" mariadb redis-server fail2ban; do
        svc_status="$(systemctl is-active "$svc" 2>/dev/null)" || svc_status="not found"
        local color="$RED"; [[ "$svc_status" == "active" ]] && color="$GREEN"
        printf "    %-18s ${color}%s${NC}\n" "${svc}:" "$svc_status"
    done

    local redis_mem; redis_mem="$(redis-cli -s "$REDIS_SOCK" info memory 2>/dev/null | grep -m1 'used_memory_human:' | cut -d: -f2 | tr -d '[:space:]')" || redis_mem="n/a"
    printf "\n  Redis mem:  %s\n" "$redis_mem"

    local ssl_expiry; ssl_expiry="$(echo | openssl s_client -connect localhost:443 -servername "$DOMAIN" 2>/dev/null | openssl x509 -noout -enddate 2>/dev/null | cut -d= -f2)" || ssl_expiry="n/a"
    printf "  SSL:        %s\n" "$ssl_expiry"

    local cache_size; cache_size="$(du -sh "$CACHE_PATH" 2>/dev/null | awk '{print $1}')" || cache_size="n/a"
    printf "  FastCGI:    %s cached\n" "$cache_size"
}

# ===========================================================================
# 2) WORDPRESS
# ===========================================================================
menu_wordpress() {
    local sub="${1:-}"
    if [[ -z "$sub" ]]; then
        _header "WordPress Tools"
        printf "  1) Login (auto-login URL, no password)\n"
        printf "  2) Update all (core + plugins + themes)\n"
        printf "  3) List plugins\n"
        printf "  4) Debug mode on/off\n"
        printf "  5) Maintenance mode on/off\n"
        printf "  6) Reset admin password\n"
        printf "  7) Search & replace\n"
        printf "  8) WP-CLI (pass-through)\n"
        printf "  0) Back\n\n"
        read -rp "  Choose: " sub
        case "$sub" in
            1) sub="login" ;; 2) sub="update" ;; 3) sub="plugins" ;; 4) sub="debug" ;;
            5) sub="maintenance" ;; 6) sub="admin-pass" ;; 7) sub="search-replace" ;;
            8) sub="cli" ;; *) return 0 ;;
        esac
    fi

    case "$sub" in
        login)
            _wp_auto_login
            ;;
        update)
            log_info "Updating WordPress core, plugins, and themes..."
            wp_run core update
            wp_run plugin update --all
            wp_run theme update --all
            log_success "WordPress updated."
            ;;
        plugins)
            wp_run plugin list
            ;;
        debug)
            local current; current="$(wp_run config get WP_DEBUG --raw 2>/dev/null | tr -d '[:space:]')"
            local debug_arg="${2:-}"
            local is_on=false
            [[ "$current" == "1" || "$current" == "true" ]] && is_on=true

            if [[ "$debug_arg" == "on" ]]; then
                wp_run config set WP_DEBUG true --raw > /dev/null
                wp_run config set WP_DEBUG_LOG true --raw > /dev/null
                log_success "Debug mode → ON. Logs: $WEB_ROOT/wp-content/debug.log"
            elif [[ "$debug_arg" == "off" ]]; then
                wp_run config set WP_DEBUG false --raw > /dev/null
                wp_run config set WP_DEBUG_LOG false --raw > /dev/null
                log_success "Debug mode → OFF."
            else
                # Show status only, ask to toggle
                if $is_on; then
                    printf "  Debug mode: ${YELLOW}ON${NC}\n"
                    printf "  Log: %s/wp-content/debug.log\n" "$WEB_ROOT"
                    printf "\n  Turn off? ${DIM}az-wp wp debug off${NC}\n"
                else
                    printf "  Debug mode: ${GREEN}OFF${NC}\n"
                    printf "\n  Turn on? ${DIM}az-wp wp debug on${NC}\n"
                fi
            fi
            ;;
        maintenance)
            local mfile="$WEB_ROOT/.maintenance"
            if [[ -f "$mfile" ]]; then
                rm -f "$mfile"
                log_success "Maintenance mode OFF."
            else
                printf '<?php $upgrading = time(); ?>' > "$mfile"
                chown "$SITE_USER:$SITE_USER" "$mfile"
                log_success "Maintenance mode ON."
            fi
            ;;
        admin-pass)
            local new_pass; new_pass="$(generate_password 20)"
            wp_run user update "$(state_get WP_ADMIN_USER 2>/dev/null || echo admin)" --user_pass="$new_pass"
            log_success "Admin password changed: $new_pass"
            ;;
        search-replace)
            local old_str new_str
            read -rp "  Old string: " old_str
            read -rp "  New string: " new_str
            [[ -z "$old_str" || -z "$new_str" ]] && { log_warn "Empty input."; return; }
            log_info "Dry run..."
            wp_run search-replace "$old_str" "$new_str" --dry-run
            confirm "Apply changes?" || return 0
            wp_run search-replace "$old_str" "$new_str"
            log_success "Search & replace complete."
            ;;
        cli)
            printf "  Entering WP-CLI (type 'exit' to return):\n"
            sudo -u "$SITE_USER" wp shell --path="$WEB_ROOT" 2>/dev/null || \
                sudo -u "$SITE_USER" bash -c "cd $WEB_ROOT && exec bash"
            ;;
        *) log_warn "Unknown: $sub" ;;
    esac
}

# ===========================================================================
# 3) DATABASE
# ===========================================================================
menu_database() {
    local sub="${1:-}"
    if [[ -z "$sub" ]]; then
        _header "Database Tools"
        printf "  1) phpMyAdmin (open login URL)\n"
        printf "  2) Database info (credentials, paths)\n"
        printf "  3) Optimize tables\n"
        printf "  4) MySQL CLI\n"
        printf "  0) Back\n\n"
        read -rp "  Choose: " sub
        case "$sub" in
            1) sub="pma" ;; 2) sub="info" ;;
            3) sub="optimize" ;; 4) sub="cli" ;; *) return 0 ;;
        esac
    fi

    case "$sub" in
        pma)
            local pma_path pma_expiry
            pma_path="$(state_get PMA_PATH 2>/dev/null)" || pma_path=""
            pma_expiry="$(state_get PMA_EXPIRY 2>/dev/null)" || pma_expiry=""
            if [[ -z "$pma_path" || ! -f /etc/nginx/az-wp-pma.conf ]]; then
                _pma_enable
            else
                printf "\n  ${BOLD}phpMyAdmin:${NC} https://%s%s/\n" "$DOMAIN" "$pma_path"
                [[ -n "$pma_expiry" ]] && printf "  ${DIM}Expires: %s${NC}\n" "$pma_expiry"
                printf "  ${DIM}Regenerate: az-wp advanced pma-config regenerate${NC}\n\n"
            fi
            ;;
        optimize)
            log_info "Optimizing tables..."
            mysqlcheck --optimize -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" 2>/dev/null
            log_success "Tables optimized."
            ;;
        cli)
            mysql -u "$DB_USER" -p"$DB_PASS" "$DB_NAME"
            ;;
        info)
            _header "Database Info"
            printf "  DB Name:  %s\n" "$DB_NAME"
            printf "  DB User:  %s\n" "$DB_USER"
            printf "  DB Pass:  %s\n" "$DB_PASS"
            printf "  Backups:  /home/%s/backups/\n" "$SITE_USER"
            local pma_path; pma_path="$(state_get PMA_PATH 2>/dev/null)" || pma_path=""
            [[ -n "$pma_path" ]] && printf "  PMA URL:  https://%s%s/\n" "$DOMAIN" "$pma_path"
            ;;
        *) log_warn "Unknown: $sub" ;;
    esac
}

# ===========================================================================
# 4) CACHE
# ===========================================================================
menu_cache() {
    local sub="${1:-}"
    if [[ -z "$sub" ]]; then
        _header "Cache Management"
        printf "  1) Purge all (FastCGI + Redis + OPcache)\n"
        printf "  2) Purge FastCGI only\n"
        printf "  3) Purge Redis only\n"
        printf "  4) Purge OPcache (restart PHP-FPM)\n"
        printf "  5) Cache stats\n"
        printf "  0) Back\n\n"
        read -rp "  Choose: " sub
        case "$sub" in
            1) sub="purge" ;; 2) sub="purge-fcgi" ;; 3) sub="purge-redis" ;;
            4) sub="purge-opcache" ;; 5) sub="stats" ;; *) return 0 ;;
        esac
    fi

    case "$sub" in
        purge)
            rm -rf "${CACHE_PATH:?}"/* 2>/dev/null || true
            redis-cli -s "$REDIS_SOCK" FLUSHDB > /dev/null 2>&1 || true
            systemctl restart "php${PHP_VERSION}-fpm" 2>/dev/null
            _refresh_cache_stats
            log_success "FastCGI + Redis + OPcache purged."
            ;;
        purge-fcgi)
            rm -rf "${CACHE_PATH:?}"/* 2>/dev/null || true
            _refresh_cache_stats
            log_success "FastCGI cache purged."
            ;;
        purge-redis)
            redis-cli -s "$REDIS_SOCK" FLUSHDB > /dev/null 2>&1 || true
            log_success "Redis cache purged."
            ;;
        purge-opcache)
            systemctl restart "php${PHP_VERSION}-fpm" 2>/dev/null
            log_success "OPcache purged (PHP-FPM restarted)."
            ;;
        stats)
            local fcgi_size; fcgi_size="$(du -sh "$CACHE_PATH" 2>/dev/null | awk '{print $1}')" || fcgi_size="0"
            local fcgi_count; fcgi_count="$(find "$CACHE_PATH" -type f 2>/dev/null | wc -l)" || fcgi_count="0"
            local redis_mem; redis_mem="$(redis-cli -s "$REDIS_SOCK" info memory 2>/dev/null | grep -m1 'used_memory_human:' | cut -d: -f2 | tr -d '[:space:]')" || redis_mem="n/a"
            local redis_keys; redis_keys="$(redis-cli -s "$REDIS_SOCK" dbsize 2>/dev/null | grep -oP '\d+')" || redis_keys="0"
            _header "Cache Stats"
            printf "  FastCGI:  %s (%s files)\n" "$fcgi_size" "$fcgi_count"
            printf "  Redis:    %s (%s keys)\n" "$redis_mem" "$redis_keys"
            printf "  OPcache:  ${DIM}(purge via option 4 or 'az-wp cache purge-opcache')${NC}\n"
            ;;
        *) log_warn "Unknown: $sub" ;;
    esac
}

# ===========================================================================
# 5) BACKUP
# ===========================================================================
menu_backup() {
    local sub="${1:-}"
    local backup_dir="/home/${SITE_USER}/backups"
    local max_backups=5
    mkdir -p "$backup_dir"

    if [[ -z "$sub" ]]; then
        _header "Backup & Restore"
        # Show current status
        local bk_count; bk_count="$(ls "$backup_dir"/*-db-*.sql.gz 2>/dev/null | wc -l || echo 0)"
        local bk_total; bk_total="$(du -sh "$backup_dir" 2>/dev/null | awk '{print $1}')" || bk_total="0"
        local bk_sched="not scheduled"
        [[ -f /etc/cron.d/az-wp-backup ]] && bk_sched="$(head -1 /etc/cron.d/az-wp-backup | sed 's/^# az-wp: //' || true)"
        printf "  Backups: %s (max %s) | Size: %s | Auto: %s\n\n" "$bk_count" "$max_backups" "$bk_total" "$bk_sched"

        printf "  ${BOLD}Create:${NC}\n"
        printf "  1) Full backup (DB + files)\n"
        printf "  2) Database only\n"
        printf "  3) Source only (files, no DB)\n\n"
        printf "  ${BOLD}Manage:${NC}\n"
        printf "  4) List backups\n"
        printf "  5) Restore from backup\n"
        printf "  6) Schedule auto backup\n"
        printf "  0) Back\n\n"
        read -rp "  Choose: " sub
        case "$sub" in
            1) sub="full" ;; 2) sub="db" ;; 3) sub="source" ;;
            4) sub="list" ;; 5) sub="restore" ;; 6) sub="schedule" ;;
            *) return 0 ;;
        esac
    fi

    case "$sub" in
        full)
            _backup_run "full"
            ;;
        db)
            _backup_run "db"
            ;;
        source)
            _backup_run "source"
            ;;
        list)
            _header "Available Backups"
            local i=0
            for f in $(ls -t "$backup_dir"/*.gz 2>/dev/null); do
                i=$((i + 1))
                local name; name="$(basename "$f")"
                local size; size="$(stat -c%s "$f" 2>/dev/null || echo 0)"
                local date_str; date_str="$(stat -c%y "$f" 2>/dev/null | cut -d. -f1)"
                local type="?"
                [[ "$name" == *-db-* ]] && type="DB"
                [[ "$name" == *-files-* ]] && type="FILES"
                [[ "$name" == *-source-* ]] && type="SOURCE"
                printf "  %2d) %-6s %-12s %-20s %s\n" "$i" "$type" "$(format_size "$size")" "$date_str" "$name"
            done
            [[ $i -eq 0 ]] && printf "  (no backups found)\n"
            printf "\n  Total: %s | Path: %s\n" "$(du -sh "$backup_dir" 2>/dev/null | awk '{print $1}')" "$backup_dir"
            ;;
        restore)
            _header "Restore from Backup"
            # List available backups for selection
            local files=()
            local i=0
            for f in $(ls -t "$backup_dir"/*.gz 2>/dev/null); do
                i=$((i + 1))
                files+=("$f")
                local name; name="$(basename "$f")"
                local size; size="$(stat -c%s "$f" 2>/dev/null || echo 0)"
                local type="?"
                [[ "$name" == *-db-* ]] && type="${CYAN}DB${NC}"
                [[ "$name" == *-files-* ]] && type="${YELLOW}FULL${NC}"
                [[ "$name" == *-source-* ]] && type="${GREEN}SRC${NC}"
                printf "  %2d) ${type}  %-12s %s\n" "$i" "$(format_size "$size")" "$name"
            done
            if [[ $i -eq 0 ]]; then
                log_info "No backups found in $backup_dir"
                return 0
            fi
            printf "\n"
            local choice
            read -rp "  Select backup number (0=back): " choice
            [[ -z "$choice" || "$choice" == "0" ]] && return 0

            if [[ "$choice" =~ ^[0-9]+$ ]] && [[ $choice -ge 1 && $choice -le $i ]]; then
                local file="${files[$((choice - 1))]}"
                local fname; fname="$(basename "$file")"
                printf "\n  Selected: ${BOLD}%s${NC} (%s)\n\n" "$fname" "$(format_size "$(stat -c%s "$file")")"

                if [[ "$fname" == *-db-*.sql.gz ]]; then
                    confirm "Restore DATABASE? This will OVERWRITE all data." || return 0
                    printf "  Restoring database"
                    # Use pv for progress if available, otherwise show dots
                    local fsize; fsize="$(stat -c%s "$file")"
                    if command -v pv >/dev/null 2>&1; then
                        pv -p -t -e "$file" | gunzip | mysql -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" 2>/dev/null
                    else
                        printf "..."
                        gunzip -c "$file" | mysql -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" 2>/dev/null
                    fi
                    printf "\n"
                    # Flush caches after DB restore
                    redis-cli -s "$REDIS_SOCK" FLUSHDB > /dev/null 2>&1 || true
                    log_success "Database restored from $fname"

                elif [[ "$fname" == *-files-*.tar.gz || "$fname" == *-source-*.tar.gz ]]; then
                    confirm "Restore FILES? This will OVERWRITE site files." || return 0
                    printf "  Extracting"
                    if command -v pv >/dev/null 2>&1; then
                        pv -p -t -e "$file" | tar xzf - -C "$(dirname "$WEB_ROOT")" 2>/dev/null
                    else
                        printf "..."
                        tar xzf "$file" -C "$(dirname "$WEB_ROOT")" 2>/dev/null
                    fi
                    printf "\n"
                    chown -R "$SITE_USER:$SITE_USER" "$WEB_ROOT"
                    systemctl restart "php${PHP_VERSION}-fpm" 2>/dev/null
                    log_success "Files restored from $fname"
                fi
            else
                log_warn "Invalid selection."
            fi
            ;;
        schedule)
            _header "Backup Schedule"
            if [[ -f /etc/cron.d/az-wp-backup ]]; then
                printf "  Current: ${GREEN}%s${NC}\n\n" "$(head -1 /etc/cron.d/az-wp-backup | sed 's/^# az-wp: //')"
            else
                printf "  Current: ${DIM}not scheduled${NC}\n\n"
            fi

            printf "  1) Daily (every day at 3:00 AM)\n"
            printf "  2) Every 2 days\n"
            printf "  3) Mon-Wed-Fri\n"
            printf "  4) Tue-Thu-Sat\n"
            printf "  5) Weekly (Sunday 3:00 AM)\n"
            printf "  6) Disable auto backup\n"
            printf "  0) Back\n\n"
            local sched_choice
            read -rp "  Choose: " sched_choice

            local cron_file="/etc/cron.d/az-wp-backup"
            local cron_cmd="root /usr/local/bin/az-wp backup full >> /var/log/az-wp/backup.log 2>&1"
            case "$sched_choice" in
                1) printf '# az-wp: daily backup at 3:00 AM\n0 3 * * * %s\n' "$cron_cmd" > "$cron_file"
                   log_success "Scheduled: daily at 3:00 AM" ;;
                2) printf '# az-wp: backup every 2 days at 3:00 AM\n0 3 */2 * * %s\n' "$cron_cmd" > "$cron_file"
                   log_success "Scheduled: every 2 days at 3:00 AM" ;;
                3) printf '# az-wp: backup Mon-Wed-Fri at 3:00 AM\n0 3 * * 1,3,5 %s\n' "$cron_cmd" > "$cron_file"
                   log_success "Scheduled: Mon-Wed-Fri at 3:00 AM" ;;
                4) printf '# az-wp: backup Tue-Thu-Sat at 3:00 AM\n0 3 * * 2,4,6 %s\n' "$cron_cmd" > "$cron_file"
                   log_success "Scheduled: Tue-Thu-Sat at 3:00 AM" ;;
                5) printf '# az-wp: weekly backup Sunday at 3:00 AM\n0 3 * * 0 %s\n' "$cron_cmd" > "$cron_file"
                   log_success "Scheduled: weekly (Sunday 3:00 AM)" ;;
                6) rm -f "$cron_file"
                   log_success "Auto backup disabled." ;;
                *) return 0 ;;
            esac
            [[ -f "$cron_file" ]] && chmod 644 "$cron_file"
            printf "  ${DIM}Retention: last %s backups kept${NC}\n" "$max_backups"
            ;;
        *) log_warn "Unknown: $sub" ;;
    esac
}

# ---------------------------------------------------------------------------
# Backup runner: handles full, db, source with progress
# ---------------------------------------------------------------------------
_backup_run() {
    local mode="$1"  # full, db, source
    local backup_dir="/home/${SITE_USER}/backups"
    local ts; ts="$(date +%Y%m%d-%H%M%S)"
    local start_ts; start_ts="$(date +%s)"

    case "$mode" in
        full) log_info "Starting full backup (DB + files)..." ;;
        db)   log_info "Starting database backup..." ;;
        source) log_info "Starting source backup (files only)..." ;;
    esac

    # DB backup (for full and db modes)
    if [[ "$mode" == "full" || "$mode" == "db" ]]; then
        local db_file="$backup_dir/${DOMAIN}-db-${ts}.sql.gz"
        log_sub "Dumping database..."

        # Show progress: estimate DB size first
        local db_est
        db_est="$(mysql -u "$DB_USER" -p"$DB_PASS" -N -e \
            "SELECT ROUND(SUM(data_length + index_length)/1048576) FROM information_schema.tables WHERE table_schema='$DB_NAME'" 2>/dev/null || echo "?")"
        log_sub "Database size: ~${db_est}MB"

        ionice -c3 nice -n 19 mysqldump --single-transaction --quick --lock-tables=false \
            --routines --triggers --max-allowed-packet=256M \
            -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" 2>/dev/null \
            | ionice -c3 nice -n 19 gzip > "$db_file"

        local db_size; db_size="$(stat -c%s "$db_file" 2>/dev/null || echo 0)"
        log_sub "DB backup: $(format_size "$db_size") → $db_file"
    fi

    # Files backup (for full and source modes)
    if [[ "$mode" == "full" || "$mode" == "source" ]]; then
        local files_file="$backup_dir/${DOMAIN}-${mode}-${ts}.tar.gz"
        if [[ "$mode" == "full" ]]; then
            files_file="$backup_dir/${DOMAIN}-files-${ts}.tar.gz"
        else
            files_file="$backup_dir/${DOMAIN}-source-${ts}.tar.gz"
        fi

        # Estimate size
        local src_est
        src_est="$(du -sh "$WEB_ROOT" 2>/dev/null | awk '{print $1}')" || src_est="?"
        log_sub "Compressing files (~${src_est} uncompressed)..."

        ionice -c3 nice -n 19 tar czf "$files_file" \
            --exclude='wp-content/cache/*' \
            --exclude='wp-content/updraft/*' \
            --exclude='wp-content/upgrade/*' \
            --exclude='wp-content/ai1wm-backups/*' \
            --exclude='.git' \
            --exclude='node_modules' \
            --exclude='*.log' \
            -C "$(dirname "$WEB_ROOT")" "$(basename "$WEB_ROOT")" 2>/dev/null || true

        local files_size; files_size="$(stat -c%s "$files_file" 2>/dev/null || echo 0)"
        log_sub "Files backup: $(format_size "$files_size") → $files_file"
    fi

    local elapsed=$(( $(date +%s) - start_ts ))
    local elapsed_str="${elapsed}s"
    [[ $elapsed -ge 60 ]] && elapsed_str="$((elapsed / 60))m $((elapsed % 60))s"
    log_success "Backup complete (${elapsed_str})"

    # Retention
    _backup_cleanup "$backup_dir"
}

# ---------------------------------------------------------------------------
# Backup cleanup: keep only last N backup pairs
# ---------------------------------------------------------------------------
_backup_cleanup() {
    local dir="$1"
    local max=5

    # Clean DB backups (keep newest 5)
    local db_files
    db_files="$(ls -t "$dir"/*-db-*.sql.gz 2>/dev/null)" || return 0
    local count=0
    local f
    while IFS= read -r f; do
        count=$((count + 1))
        if [[ $count -gt $max ]]; then
            local size; size="$(stat -c%s "$f" 2>/dev/null || echo 0)"
            rm -f "$f"
            log_sub "Removed old backup: $(basename "$f") ($(format_size "$size"))"
        fi
    done <<< "$db_files"

    # Clean file backups (keep newest 5)
    local file_files
    file_files="$(ls -t "$dir"/*-files-*.tar.gz 2>/dev/null)" || return 0
    count=0
    while IFS= read -r f; do
        count=$((count + 1))
        if [[ $count -gt $max ]]; then
            local size; size="$(stat -c%s "$f" 2>/dev/null || echo 0)"
            rm -f "$f"
            log_sub "Removed old backup: $(basename "$f") ($(format_size "$size"))"
        fi
    done <<< "$file_files"
}

# ===========================================================================
# 6) CRON — Full management
# ===========================================================================
menu_cron() {
    local sub="${1:-}"
    if [[ -z "$sub" ]]; then
        _header "Cron Management"
        _cron_show_all
        printf "\n  ${BOLD}Actions:${NC}\n"
        printf "  1) Add cron job (paste cron line)\n"
        printf "  2) Install AffiliateCMS crons (15 jobs)\n"
        printf "  3) Remove a cron job\n"
        printf "  4) Remove ALL crons & reinstall preset\n"
        printf "  5) Edit a cron job\n"
        printf "  6) Test a cron (run now)\n"
        printf "  0) Back\n\n"
        read -rp "  Choose: " sub
        case "$sub" in
            1) sub="add" ;; 2) sub="preset" ;; 3) sub="remove" ;;
            4) sub="reset" ;; 5) sub="edit" ;; 6) sub="test" ;;
            *) return 0 ;;
        esac
    fi

    case "$sub" in
        list) _cron_show_all ;;

        add)
            printf "\n  Paste a full cron line (schedule + command):\n"
            printf "  ${DIM}Example: */5 * * * * curl -s \"https://${DOMAIN}/wp-json/acms/v1/cron/scrape\"${NC}\n\n"
            local cron_line
            read -rp "  > " cron_line
            [[ -z "$cron_line" ]] && { log_warn "Empty input."; return 0; }
            _cron_add_line "$cron_line"
            ;;

        preset)
            _cron_install_preset
            ;;

        remove)
            local name="${2:-}"
            if [[ -z "$name" ]]; then
                _cron_show_numbered
                read -rp "  Number or name to remove (0=back): " name
                [[ -z "$name" || "$name" == "0" ]] && return 0
                # If numeric, resolve to filename
                if [[ "$name" =~ ^[0-9]+$ ]]; then
                    name="$(_cron_get_by_number "$name")"
                    [[ -z "$name" ]] && { log_warn "Invalid number."; return 0; }
                fi
            fi
            [[ "$name" != az-wp-* ]] && name="az-wp-${name}"
            local target="/etc/cron.d/${name}"
            if [[ -f "$target" ]]; then
                printf "  %s\n" "$(cat "$target")"
                confirm "Remove this cron?" || return 0
                rm -f "$target"
                log_success "Removed: $name"
            else
                log_warn "Not found: $target"
            fi
            ;;

        reset)
            _header "Reset All Crons"
            local count=0
            for f in /etc/cron.d/az-wp-*; do
                [[ ! -f "$f" ]] && continue
                local bn; bn="$(basename "$f")"
                # Keep system crons
                [[ "$bn" == "az-wp-cron" || "$bn" == "az-wp-backup" || "$bn" == "az-wp-pma-expire" ]] && continue
                count=$((count + 1))
            done
            printf "  Will remove %d plugin cron jobs.\n" "$count"
            printf "  ${DIM}Keeping: az-wp-cron, az-wp-backup, az-wp-pma-expire${NC}\n"
            printf "  Then reinstall AffiliateCMS preset.\n\n"
            confirm "Proceed?" || return 0
            for f in /etc/cron.d/az-wp-*; do
                [[ ! -f "$f" ]] && continue
                local bn; bn="$(basename "$f")"
                [[ "$bn" == "az-wp-cron" || "$bn" == "az-wp-backup" || "$bn" == "az-wp-pma-expire" ]] && continue
                rm -f "$f"
            done
            log_success "Removed $count plugin cron jobs."
            _cron_install_preset
            ;;

        edit)
            local name="${2:-}"
            if [[ -z "$name" ]]; then
                _cron_show_numbered
                read -rp "  Number or name to edit (0=back): " name
                [[ -z "$name" || "$name" == "0" ]] && return 0
                if [[ "$name" =~ ^[0-9]+$ ]]; then
                    name="$(_cron_get_by_number "$name")"
                    [[ -z "$name" ]] && { log_warn "Invalid number."; return 0; }
                fi
            fi
            [[ "$name" != az-wp-* ]] && name="az-wp-${name}"
            local target="/etc/cron.d/${name}"
            if [[ ! -f "$target" ]]; then
                log_warn "Not found: $target"
                return 0
            fi
            printf "\n  Current:\n"
            cat "$target" | sed 's/^/  /'
            printf "\n  Enter new cron line (or ENTER to keep):\n"
            local new_line
            read -rp "  > " new_line
            if [[ -n "$new_line" ]]; then
                local desc; desc="$(head -1 "$target" | sed 's/^# //' || true)"
                local sched cmd
                sched="$(printf '%s' "$new_line" | awk '{print $1,$2,$3,$4,$5}')"
                cmd="$(printf '%s' "$new_line" | awk '{for(i=6;i<=NF;i++) printf "%s ", $i}')"
                cmd="${cmd% }"
                [[ "$cmd" != *">/dev/null"* ]] && cmd="$cmd > /dev/null 2>&1"
                printf '# %s\n%s root %s\n' "$desc" "$sched" "$cmd" > "$target"
                chmod 644 "$target"
                log_success "Updated: $name"
            fi
            ;;

        test)
            local name="${2:-}"
            if [[ -z "$name" ]]; then
                _cron_show_numbered
                read -rp "  Number or name to test (0=back): " name
                [[ -z "$name" || "$name" == "0" ]] && return 0
                if [[ "$name" =~ ^[0-9]+$ ]]; then
                    name="$(_cron_get_by_number "$name")"
                    [[ -z "$name" ]] && { log_warn "Invalid number."; return 0; }
                fi
            fi
            [[ "$name" != az-wp-* ]] && name="az-wp-${name}"
            local target="/etc/cron.d/${name}"
            if [[ ! -f "$target" ]]; then
                log_warn "Not found: $target"
                return 0
            fi
            # Extract command (skip schedule fields + "root")
            local raw_line
            raw_line="$(grep -v '^#' "$target" | grep -v '^$' | head -1 || true)"
            # Fields: 1-5=schedule, 6=user, 7+=command
            local cmd
            cmd="$(printf '%s' "$raw_line" | awk '{for(i=7;i<=NF;i++) printf "%s ", $i}')"
            # Strip ALL redirects so we see output
            cmd="$(printf '%s' "$cmd" | sed 's|>>* *[^ ]*||g; s|2>&1||g; s|> */dev/null||g')"
            cmd="${cmd% }"

            # Auto-replace invalid/test tokens with real API token
            if [[ "$cmd" == *"token="* ]]; then
                local real_token
                real_token="$(wp_run option get acms_api_token 2>/dev/null | tr -d '[:space:]')" || real_token=""
                if [[ -n "$real_token" ]]; then
                    cmd="$(printf '%s' "$cmd" | sed "s|token=[^\"&]*|token=${real_token}|g")"
                fi
            fi

            printf "  ${DIM}Command:${NC} %s\n\n" "$cmd"
            printf "  ${BOLD}Output:${NC}\n"
            eval "$cmd" 2>&1 | head -30 | sed 's/^/  /'
            local exit_code=$?
            printf "\n  ${DIM}Exit code: %d${NC}\n" "$exit_code"
            ;;

        remove-all)
            printf "  ${DIM}System crons (wp-cron, backup, pma-expire) will be kept.${NC}\n"
            confirm "Remove ALL plugin cron jobs?" || return 0
            local count=0
            for f in /etc/cron.d/az-wp-*; do
                [[ ! -f "$f" ]] && continue
                local bn; bn="$(basename "$f")"
                [[ "$bn" == "az-wp-cron" || "$bn" == "az-wp-backup" || "$bn" == "az-wp-pma-expire" ]] && continue
                rm -f "$f"
                count=$((count + 1))
            done
            log_success "Removed $count plugin cron jobs."
            ;;

        *) log_warn "Unknown: $sub" ;;
    esac
}

# ---------------------------------------------------------------------------
# Cron helpers
# ---------------------------------------------------------------------------

# Show all crons with nice formatting
_cron_show_all() {
    printf "\n"
    local found=0

    # System crons
    local has_system=0
    for f in /etc/cron.d/az-wp-cron /etc/cron.d/az-wp-backup /etc/cron.d/az-wp-pma-expire; do
        [[ ! -f "$f" ]] && continue
        if [[ $has_system -eq 0 ]]; then
            printf "  ${BOLD}System:${NC}\n"
            has_system=1
        fi
        found=1
        local name; name="$(basename "$f")"
        local desc; desc="$(head -1 "$f" | sed 's/^# az-wp[: ]*//' || true)"
        local sched; sched="$(grep -v '^#' "$f" | grep -v '^$' | head -1 | awk '{print $1,$2,$3,$4,$5}' || true)"
        printf "    ${DIM}%-28s${NC} %-14s %s\n" "$name" "$sched" "$desc"
    done

    # AffiliateCMS / custom crons (grouped by tier)
    local has_scrape=0 has_ai=0 has_cache=0 has_other=0

    for f in /etc/cron.d/az-wp-*; do
        [[ ! -f "$f" ]] && continue
        local bn; bn="$(basename "$f")"
        [[ "$bn" == "az-wp-cron" || "$bn" == "az-wp-backup" || "$bn" == "az-wp-pma-expire" ]] && continue
        found=1

        local desc; desc="$(head -1 "$f" | sed 's/^# az-wp cron: //' || true)"
        local sched; sched="$(grep -v '^#' "$f" | grep -v '^$' | head -1 | awk '{print $1,$2,$3,$4,$5}' || true)"

        # Group by type
        if [[ "$bn" == *scrape* || "$bn" == *queue* || "$bn" == *bulk* ]]; then
            if [[ $has_scrape -eq 0 ]]; then printf "\n  ${BOLD}Scraping Pipeline:${NC}\n"; has_scrape=1; fi
        elif [[ "$bn" == *ai* ]]; then
            if [[ $has_ai -eq 0 ]]; then printf "\n  ${BOLD}AI Generation:${NC}\n"; has_ai=1; fi
        elif [[ "$bn" == *cache* ]]; then
            if [[ $has_cache -eq 0 ]]; then printf "\n  ${BOLD}Cache:${NC}\n"; has_cache=1; fi
        else
            if [[ $has_other -eq 0 ]]; then printf "\n  ${BOLD}Custom:${NC}\n"; has_other=1; fi
        fi

        printf "    ${GREEN}%-28s${NC} %-14s %s\n" "$bn" "$sched" "$desc"
    done

    if [[ "$found" -eq 0 ]]; then
        printf "  ${DIM}(no cron jobs)${NC}\n"
    fi

    # Show total count
    local total; total="$(ls /etc/cron.d/az-wp-* 2>/dev/null | wc -l || echo 0)"
    printf "\n  ${DIM}Total: %s cron jobs${NC}\n" "$total"
}

# Show numbered list for selection
_cron_show_numbered() {
    printf "\n"
    local i=0
    for f in /etc/cron.d/az-wp-*; do
        [[ ! -f "$f" ]] && continue
        [[ "$(basename "$f")" == "az-wp-cron" ]] && continue
        i=$((i + 1))
        local name; name="$(basename "$f")"
        local desc; desc="$(head -1 "$f" | sed 's/^# az-wp[: ]*//' || true)"
        printf "  %2d) %-28s %s\n" "$i" "$name" "$desc"
    done
    [[ $i -eq 0 ]] && printf "  (no custom cron jobs)\n"
    printf "\n"
}

# Get cron filename by number
_cron_get_by_number() {
    local num="$1"
    local i=0
    for f in /etc/cron.d/az-wp-*; do
        [[ ! -f "$f" ]] && continue
        [[ "$(basename "$f")" == "az-wp-cron" ]] && continue
        i=$((i + 1))
        if [[ $i -eq $num ]]; then
            basename "$f"
            return 0
        fi
    done
    return 1
}

# Add a single cron from a raw line
_cron_add_line() {
    local cron_line="$1"

    # Auto-generate name from URL path
    local cron_name
    cron_name="$(printf '%s' "$cron_line" | grep -oP '/v1/[^?"]+' | sed 's|/v1/||;s|/|-|g' | head -1 || true)"
    [[ -z "$cron_name" ]] && cron_name="custom-$(openssl rand -hex 3)"

    # Extract schedule (first 5 fields) and command (rest)
    local sched cmd
    sched="$(printf '%s' "$cron_line" | awk '{print $1,$2,$3,$4,$5}')"
    cmd="$(printf '%s' "$cron_line" | awk '{for(i=6;i<=NF;i++) printf "%s ", $i}')"
    cmd="${cmd% }"

    # Strip existing redirect (will re-add at the end)
    cmd="$(printf '%s' "$cmd" | sed 's|>>* */dev/null[^"]*||; s|2>&1||g')"
    cmd="${cmd% }"

    # Auto-add --resolve if curl without it (loopback optimization)
    if [[ "$cmd" == *curl* && "$cmd" != *--resolve* && "$cmd" == *"${DOMAIN}"* ]]; then
        cmd="$(printf '%s' "$cmd" | sed "s|curl |curl -sk --resolve ${DOMAIN}:443:127.0.0.1 --max-time 30 |")"
    fi

    # Always add clean redirect
    cmd="$cmd > /dev/null 2>&1"

    local cron_file="/etc/cron.d/az-wp-${cron_name}"
    printf '# az-wp cron: %s\n%s root %s\n' \
        "$cron_name" "$sched" "$cmd" > "$cron_file"
    chmod 644 "$cron_file"
    log_success "Created: $cron_file"
}

# Install AffiliateCMS preset (15 cron jobs)
_cron_install_preset() {
    _header "AffiliateCMS Cron Preset"

    # Get API token
    local api_token
    api_token="$(wp_run option get acms_api_token 2>/dev/null | tr -d '[:space:]')" || api_token=""

    if [[ -z "$api_token" ]]; then
        printf "  ${YELLOW}AffiliateCMS API token not found.${NC}\n"
        read -rp "  Enter API token: " api_token
        [[ -z "$api_token" ]] && { log_warn "Token required. Skipped."; return 0; }
    else
        printf "  API token: ${GREEN}found${NC}\n"
    fi

    # Loopback curl command (bypasses Cloudflare, connects to localhost)
    local base="curl -sk --resolve ${DOMAIN}:443:127.0.0.1"
    local url="https://${DOMAIN}"

    # All preset crons: name|schedule|endpoint|max_time|method|description
    # Tier 1: Pipeline (every 2 min, staggered with sleep offsets)
    # Tier 2: AI Generation (every 5 min, staggered)
    # Tier 3: Maintenance (background — less frequent)
    #
    # Stagger pattern: related crons offset by 20-30s to avoid race conditions
    # scrape(0s) → process-scheduled(20s) → scrape-monitor(40s) → queue-processor(60s) → queue-monitor(80s)
    # product-ai(0s) → post-ai(30s) → category-ai(60s) → brand-ai(90s) → brand-category-ai(120s)
    local presets=(
        "scrape|*/2 * * * *||/wp-json/acms/v1/automation/scrape|30|GET|Scrape dispatcher"
        "process-scheduled|*/2 * * * *|sleep 20 && |/wp-json/acms/v1/automation/process-scheduled|30|GET|Process scheduled (+20s)"
        "scrape-monitor|*/2 * * * *|sleep 40 && |/wp-json/acms/v1/cron/scrape-monitor|30|GET|Scrape monitor (+40s)"
        "queue-processor|*/2 * * * *|sleep 60 && |/wp-json/acms-cat/v1/cron/queue-processor|60|GET|Queue processor (+60s)"
        "queue-monitor|*/2 * * * *|sleep 80 && |/wp-json/acms-cat/v1/cron/queue-monitor|30|GET|Queue monitor (+80s)"
        "product-ai|*/5 * * * *||/wp-json/acms/v1/cron/product-ai|30|GET|Product AI"
        "post-ai|*/5 * * * *|sleep 30 && |/wp-json/acms/v1/cron/post-ai|30|GET|Post AI (+30s)"
        "category-ai|*/5 * * * *|sleep 60 && |/wp-json/acms-cat/v1/cron/category-ai|60|GET|Category AI (+60s)"
        "brand-ai|*/5 * * * *|sleep 90 && |/wp-json/acms/v1/cron/brand-ai|30|GET|Brand AI (+90s)"
        "brand-category-ai|*/5 * * * *|sleep 120 && |/wp-json/acms-cat/v1/cron/brand-category-ai|30|GET|Brand category AI (+120s)"
        "quick-update|*/30 * * * *||/wp-json/acms/v1/cron/quick-update|60|GET|Quick update"
        "retry-stuck|*/10 * * * *||/wp-json/acms-cat/v1/cron/retry-stuck|30|GET|Retry stuck"
        "date-update|0 3 * * *||/wp-json/acms/v1/cron/date-update|30|GET|Date update (daily 3am)"
        "bulk-update|* * * * *||/wp-json/acms-cat/v1/cron/bulk-update-worker|90|GET|Bulk update worker"
        "cache-preload|0 3 * * 0||/wp-json/acms/v1/cache/preload|30|GET|Cache preload (weekly)"
        "cache-refresh|0 */4 * * *||/wp-json/acms/v1/cache/smart-refresh|30|POST|Cache refresh (4h)"
        "cache-resume|*/30 * * * *||/wp-json/acms/v1/cache/resume-queue|30|POST|Cache resume queue"
    )

    printf "\n  ${BOLD}%-14s %-30s %s${NC}\n" "Schedule" "Description" "Endpoint"
    printf "  ──────────────────────────────────────────────────────────\n"

    printf "\n  ${DIM}Tier 1: Pipeline (every 2 min, staggered):${NC}\n"
    for p in "${presets[@]}"; do
        IFS='|' read -r name sched sleep_prefix endpoint max_time method desc <<< "$p"
        [[ "$sched" != "*/2"* ]] && continue
        printf "    %-14s %-30s %s\n" "$sched" "$desc" "$endpoint"
    done

    printf "\n  ${DIM}Tier 2: AI Generation (every 5 min, staggered):${NC}\n"
    for p in "${presets[@]}"; do
        IFS='|' read -r name sched sleep_prefix endpoint max_time method desc <<< "$p"
        [[ "$sched" != "*/5"* ]] && continue
        printf "    %-14s %-30s %s\n" "$sched" "$desc" "$endpoint"
    done

    printf "\n  ${DIM}Tier 3: Maintenance (background):${NC}\n"
    for p in "${presets[@]}"; do
        IFS='|' read -r name sched sleep_prefix endpoint max_time method desc <<< "$p"
        [[ "$sched" == "*/2"* || "$sched" == "*/5"* ]] && continue
        printf "    %-14s %-30s %s\n" "$sched" "$desc" "$endpoint"
    done

    printf "\n  Total: %d cron jobs\n" "${#presets[@]}"
    printf "  All use ${GREEN}--resolve localhost${NC} (bypass Cloudflare, direct to server)\n\n"

    confirm "Install all ${#presets[@]} cron jobs?" || return 0

    local count=0
    for p in "${presets[@]}"; do
        IFS='|' read -r name sched sleep_prefix endpoint max_time method desc <<< "$p"
        local cron_file="/etc/cron.d/az-wp-${name}"
        local curl_cmd="${base} --max-time ${max_time}"
        [[ "$method" == "POST" ]] && curl_cmd="${curl_cmd} -X POST"
        printf '# az-wp cron: %s\n%s root %s%s "%s%s?token=%s" > /dev/null 2>&1\n' \
            "$desc" "$sched" "$sleep_prefix" "$curl_cmd" "$url" "$endpoint" "$api_token" > "$cron_file"
        chmod 644 "$cron_file"
        count=$((count + 1))
    done

    log_success "Installed $count AffiliateCMS cron jobs."
    printf "\n"
    _cron_show_all
}

# ===========================================================================
# 7) DOMAIN CHANGE
# ===========================================================================
menu_domain() {
    local sub="${1:-change}"

    _header "Domain Management"
    printf "  Current domain: ${GREEN}%s${NC}\n" "$DOMAIN"
    printf "  Web root:       %s\n" "$WEB_ROOT"
    printf "  Cache path:     %s\n\n" "$CACHE_PATH"

    local new_domain
    read -rp "  New domain: " new_domain
    [[ -z "$new_domain" ]] && { log_warn "No domain entered."; return; }
    [[ "$new_domain" == "$DOMAIN" ]] && { log_warn "Same as current domain."; return; }

    local old_domain="$DOMAIN"
    local old_web_root="$WEB_ROOT"
    local new_web_root="/home/${SITE_USER}/${new_domain}"

    printf "\n  ${BOLD}Changes:${NC}\n"
    printf "    Domain:    %s → %s\n" "$old_domain" "$new_domain"
    printf "    Web root:  %s → %s\n" "$old_web_root" "$new_web_root"
    printf "    Database:  search & replace all URLs\n"
    printf "    Nginx:     new server_name + config file\n"
    printf "    SSL:       new certificate\n"
    printf "    Cron:      update all domain references\n"
    printf "    Cache:     flush all + update paths\n\n"

    confirm "Proceed with domain change?" || return 0

    # === Step 1: Database search & replace ===
    log_sub "1/9 Replacing in database: $old_domain → $new_domain ..."
    wp_run search-replace "$old_domain" "$new_domain" --all-tables --precise > /dev/null
    wp_run search-replace "http://$old_domain" "https://$new_domain" --all-tables --precise > /dev/null

    # === Step 2: WordPress URLs ===
    log_sub "2/9 Updating WordPress site URL..."
    wp_run option update siteurl "https://$new_domain" > /dev/null
    wp_run option update home "https://$new_domain" > /dev/null

    # === Step 3: Rename web root directory ===
    log_sub "3/9 Renaming web root..."
    if [[ "$old_web_root" != "$new_web_root" && -d "$old_web_root" ]]; then
        mv "$old_web_root" "$new_web_root"
        WEB_ROOT="$new_web_root"
    fi

    # === Step 4: Nginx config (re-render from template — safer than sed) ===
    log_sub "4/9 Rebuilding Nginx configuration..."
    local new_conf="/etc/nginx/sites-available/${new_domain}.conf"

    export DOMAIN="$new_domain" WEB_ROOT="$new_web_root" PHP_VERSION
    envsubst '$DOMAIN $WEB_ROOT $PHP_VERSION' < "${AZ_DIR}/templates/nginx/site.conf.tpl" > "$new_conf"

    # Remove old config and symlink
    rm -f "/etc/nginx/sites-available/${old_domain}.conf" 2>/dev/null
    rm -f "/etc/nginx/sites-enabled/${old_domain}.conf" 2>/dev/null
    ln -sf "$new_conf" "/etc/nginx/sites-enabled/${new_domain}.conf"

    # Re-add phpMyAdmin include if exists
    if [[ -f /etc/nginx/az-wp-pma.conf ]]; then
        sed -i '/^}$/i \    include /etc/nginx/az-wp-pma.conf;' "$new_conf" 2>/dev/null || true
    fi

    # Make sure nginx works before SSL
    nginx -t 2>/dev/null && systemctl reload nginx 2>/dev/null

    # === Step 5: SSL certificate ===
    log_sub "5/9 Issuing new SSL certificate..."
    PUBLIC_IP="$(curl -sf --max-time 5 https://ifconfig.me 2>/dev/null)" || PUBLIC_IP=""
    DOMAIN="$new_domain"
    WP_ADMIN_EMAIL="$(state_get WP_ADMIN_EMAIL 2>/dev/null)" || true
    issue_certificate 2>/dev/null || log_warn "SSL issue failed. Run 'az-wp advanced ssl issue' later."

    # === Step 6: Cron jobs ===
    log_sub "6/9 Updating cron jobs..."
    for f in /etc/cron.d/az-wp-*; do
        [[ -f "$f" ]] && sed -i "s|${old_domain}|${new_domain}|g" "$f"
    done
    # Update wp-cron path
    if [[ -f /etc/cron.d/az-wp-cron ]]; then
        sed -i "s|${old_web_root}|${new_web_root}|g" /etc/cron.d/az-wp-cron
    fi

    # === Step 7: Cache ===
    log_sub "7/9 Flushing caches..."
    rm -rf "${CACHE_PATH:?}"/* 2>/dev/null || true
    redis-cli -s "$REDIS_SOCK" FLUSHDB > /dev/null 2>&1 || true
    wp_run config set WP_CACHE_KEY_SALT "${new_domain}_" > /dev/null

    # Regenerate cache-stats.json with real data
    _refresh_cache_stats

    # Update cache-stats cron if exists
    if [[ -f /etc/cron.d/az-wp-cache-stats ]]; then
        sed -i "s|${old_web_root}|${new_web_root}|g" /etc/cron.d/az-wp-cache-stats 2>/dev/null || true
    fi

    # === Step 8: Update WordPress config ===
    log_sub "8/9 Updating wp-config.php..."
    # Update open_basedir path in PHP ini (if web root changed)
    if [[ "$old_web_root" != "$new_web_root" ]]; then
        local php_ini="/etc/php/${PHP_VERSION}/fpm/conf.d/99-az-wp.ini"
        if [[ -f "$php_ini" ]]; then
            sed -i "s|${old_web_root}|${new_web_root}|g" "$php_ini" 2>/dev/null || true
        fi
        systemctl restart "php${PHP_VERSION}-fpm" 2>/dev/null
    fi

    # Update plugin cache_path setting
    wp_run option patch update acms_general_settings cache_path "${CACHE_PATH}/" > /dev/null 2>/dev/null || true

    # === Step 9: State file ===
    log_sub "9/9 Updating state file..."
    state_set "DOMAIN" "$new_domain"
    state_set "WEB_ROOT" "$new_web_root"
    DOMAIN="$new_domain"
    WEB_ROOT="$new_web_root"

    # Reload nginx
    if nginx -t 2>/dev/null; then
        systemctl reload nginx
    else
        log_warn "Nginx config error. Run: nginx -t"
    fi

    # ==========================================================
    # VERIFICATION — check everything updated correctly
    # ==========================================================
    printf "\n"
    log_success "Domain changed: $old_domain → $new_domain"
    printf "\n${BOLD}  Verification:${NC}\n"
    printf "  ──────────────────────────────────────\n"

    # Website
    local http_code
    http_code="$(curl -sfk --resolve "${new_domain}:443:127.0.0.1" -o /dev/null -w '%{http_code}' "https://${new_domain}/" 2>/dev/null)" || http_code="000"
    if [[ "$http_code" == "200" ]]; then
        printf "  ${GREEN}OK${NC}  Website:     https://%s (HTTP %s)\n" "$new_domain" "$http_code"
    else
        printf "  ${RED}!!${NC}  Website:     https://%s (HTTP %s)\n" "$new_domain" "$http_code"
    fi

    # WP Admin
    local admin_code
    admin_code="$(curl -sfk --resolve "${new_domain}:443:127.0.0.1" -o /dev/null -w '%{http_code}' "https://${new_domain}/wp-admin/" 2>/dev/null)" || admin_code="000"
    if [[ "$admin_code" == "302" || "$admin_code" == "200" ]]; then
        printf "  ${GREEN}OK${NC}  WP Admin:    https://%s/wp-admin (HTTP %s)\n" "$new_domain" "$admin_code"
    else
        printf "  ${RED}!!${NC}  WP Admin:    https://%s/wp-admin (HTTP %s)\n" "$new_domain" "$admin_code"
    fi

    # WordPress URL
    local wp_url
    wp_url="$(wp_run option get siteurl 2>/dev/null | tr -d '[:space:]')" || wp_url="?"
    if [[ "$wp_url" == "https://${new_domain}" ]]; then
        printf "  ${GREEN}OK${NC}  WP siteurl:  %s\n" "$wp_url"
    else
        printf "  ${RED}!!${NC}  WP siteurl:  %s (expected https://%s)\n" "$wp_url" "$new_domain"
    fi

    # Web root
    if [[ -d "$new_web_root" ]]; then
        printf "  ${GREEN}OK${NC}  Web root:    %s\n" "$new_web_root"
    else
        printf "  ${RED}!!${NC}  Web root:    %s (NOT FOUND)\n" "$new_web_root"
    fi

    # SSL
    local ssl_issuer
    ssl_issuer="$(echo | openssl s_client -connect localhost:443 -servername "$new_domain" 2>/dev/null | openssl x509 -noout -issuer 2>/dev/null | cut -d= -f3)" || ssl_issuer=""
    if [[ -n "$ssl_issuer" ]]; then
        printf "  ${GREEN}OK${NC}  SSL:         %s\n" "$ssl_issuer"
    else
        printf "  ${YELLOW}--${NC}  SSL:         not issued (run: az-wp advanced ssl issue)\n"
    fi

    # Nginx config
    if nginx -t 2>/dev/null; then
        printf "  ${GREEN}OK${NC}  Nginx:       config valid\n"
    else
        printf "  ${RED}!!${NC}  Nginx:       config ERROR\n"
    fi

    # Crons — check no old domain refs
    local old_refs
    old_refs="$(grep -rl "$old_domain" /etc/cron.d/az-wp-* 2>/dev/null | wc -l)" || old_refs=0
    local cron_count
    cron_count="$(ls /etc/cron.d/az-wp-* 2>/dev/null | wc -l)" || cron_count=0
    if [[ "$old_refs" -eq 0 ]]; then
        printf "  ${GREEN}OK${NC}  Crons:       %s jobs, all updated\n" "$cron_count"
    else
        printf "  ${RED}!!${NC}  Crons:       %s files still reference %s\n" "$old_refs" "$old_domain"
    fi

    # Cache path
    local cache_setting
    cache_setting="$(wp_run option pluck acms_general_settings cache_path 2>/dev/null | tr -d '[:space:]')" || cache_setting="?"
    printf "  ${GREEN}OK${NC}  Cache path:  %s\n" "${cache_setting:-$CACHE_PATH/}"

    # Cache stats
    local stats_file="/home/${SITE_USER}/cache/cache-stats.json"
    if [[ -f "$stats_file" ]]; then
        local sf_count sf_size
        sf_count="$(python3 -c "import json; print(json.load(open('$stats_file'))['files'])" 2>/dev/null)" || sf_count="?"
        sf_size="$(python3 -c "import json; s=json.load(open('$stats_file'))['size']; print(f'{s/1048576:.1f} MB')" 2>/dev/null)" || sf_size="?"
        printf "  ${GREEN}OK${NC}  Cache stats: %s files, %s\n" "$sf_count" "$sf_size"
    else
        printf "  ${YELLOW}--${NC}  Cache stats: not generated yet\n"
    fi

    # State file
    local state_domain state_webroot
    state_domain="$(state_get DOMAIN 2>/dev/null)" || state_domain="?"
    state_webroot="$(state_get WEB_ROOT 2>/dev/null)" || state_webroot="?"
    if [[ "$state_domain" == "$new_domain" && "$state_webroot" == "$new_web_root" ]]; then
        printf "  ${GREEN}OK${NC}  State file:  DOMAIN=%s, WEB_ROOT updated\n" "$state_domain"
    else
        printf "  ${RED}!!${NC}  State file:  DOMAIN=%s, WEB_ROOT=%s\n" "$state_domain" "$state_webroot"
    fi

    # Redis
    local redis_salt
    redis_salt="$(wp_run config get WP_CACHE_KEY_SALT 2>/dev/null | tr -d '[:space:]')" || redis_salt="?"
    printf "  ${GREEN}OK${NC}  Redis salt:  %s\n" "$redis_salt"

    printf "  ──────────────────────────────────────\n\n"
}

# ===========================================================================
# 8) ADVANCED
# ===========================================================================
menu_advanced() {
    local sub="${1:-}"
    if [[ -z "$sub" ]]; then
        # Interactive loop — stay in Advanced until Back
        while true; do
            _header "Advanced Settings"
            printf "  1) SSL Management\n"
            printf "  2) Security (Fail2Ban, UFW)\n"
            printf "  3) Performance (retune, TTFB, FPM, OPcache)\n"
            printf "  4) PHP Info (config, extensions, update)\n"
            printf "  5) Services (restart, reload)\n"
            printf "  6) Workers (FPM pools)\n"
            printf "  7) phpMyAdmin config\n"
            printf "  0) Back\n\n"
            read -rp "  Choose: " sub
            case "$sub" in
                1) sub="ssl" ;; 2) sub="security" ;; 3) sub="perf" ;;
                4) sub="php" ;; 5) sub="services" ;; 6) sub="workers" ;;
                7) sub="pma-config" ;; 0|"") return 0 ;; *) continue ;;
            esac
            # Run the selected sub-action then loop back to Advanced menu
            _advanced_action "$sub"
            sub=""
        done
        return 0
    fi
    _advanced_action "$sub"
}

_advanced_action() {
    local sub="$1"

    case "$sub" in
        # --- SSL ---
        ssl)
            local ssl_sub="${2:-}"
            if [[ -z "$ssl_sub" ]]; then
                _header "SSL Management"
                printf "  1) Issue/renew certificate\n"
                printf "  2) Certificate info\n"
                printf "  0) Back\n\n"
                read -rp "  Choose: " ssl_sub
                case "$ssl_sub" in 1) ssl_sub="issue" ;; 2) ssl_sub="info" ;; *) return 0 ;; esac
            fi
            case "$ssl_sub" in
                issue|renew)
                    PUBLIC_IP="$(curl -sf --max-time 5 https://ifconfig.me 2>/dev/null)" || PUBLIC_IP=""
                    issue_certificate
                    ;;
                info)
                    echo | openssl s_client -connect localhost:443 -servername "$DOMAIN" 2>/dev/null \
                        | openssl x509 -noout -subject -issuer -dates 2>/dev/null || log_warn "No SSL cert found."
                    ;;
            esac
            ;;

        # --- Security ---
        security)
            local sec_sub="${2:-}"
            if [[ -z "$sec_sub" ]]; then
                _header "Security"
                printf "  1) Run security scan (quick)\n"
                printf "  2) Run full scan (checksums + malware)\n"
                printf "  3) View scan logs\n"
                printf "  4) Fail2Ban status\n"
                printf "  5) Unban IP\n"
                printf "  6) UFW status\n"
                printf "  0) Back\n\n"
                read -rp "  Choose: " sec_sub
                case "$sec_sub" in
                    1) sec_sub="scan-daily" ;; 2) sec_sub="scan-weekly" ;;
                    3) sec_sub="scan-logs" ;; 4) sec_sub="f2b-status" ;;
                    5) sec_sub="unban" ;; 6) sec_sub="ufw" ;; *) return 0 ;;
                esac
            fi
            case "$sec_sub" in
                scan-daily|scan)
                    if [[ -x /usr/local/bin/az-wp-security-scan ]]; then
                        /usr/local/bin/az-wp-security-scan daily 2>&1
                        local rc=$?
                        local log_file="/var/log/az-wp/security/scan-$(date '+%Y-%m-%d').log"
                        [[ -f "$log_file" ]] && printf "\n" && tail -20 "$log_file" | sed 's/^/  /'
                        [[ $rc -eq 0 ]] && log_success "No issues found." || log_warn "$rc issue(s) found."
                    else
                        log_warn "Security scan not installed. Reinstall: bash /opt/az-wp/single/install.sh"
                    fi
                    ;;
                scan-weekly|scan-full)
                    if [[ -x /usr/local/bin/az-wp-security-scan ]]; then
                        log_info "Running full scan (this may take 1-5 minutes)..."
                        /usr/local/bin/az-wp-security-scan weekly 2>&1
                        local rc=$?
                        local log_file="/var/log/az-wp/security/scan-$(date '+%Y-%m-%d').log"
                        [[ -f "$log_file" ]] && printf "\n" && tail -40 "$log_file" | sed 's/^/  /'
                        [[ $rc -eq 0 ]] && log_success "No issues found." || log_warn "$rc issue(s) found."
                    else
                        log_warn "Security scan not installed."
                    fi
                    ;;
                scan-logs)
                    _header "Security Scan Logs"
                    local log_dir="/var/log/az-wp/security"
                    if [[ -d "$log_dir" ]]; then
                        ls -lht "$log_dir"/*.log 2>/dev/null | head -10 | sed 's/^/  /'
                        printf "\n  ${DIM}View latest: tail -50 %s/scan-$(date '+%%Y-%%m-%%d').log${NC}\n" "$log_dir"
                    else
                        printf "  No scan logs yet.\n"
                    fi
                    ;;
                f2b-status) fail2ban-client status 2>/dev/null; for jail in $(fail2ban-client status 2>/dev/null | grep "Jail list" | sed 's/.*://;s/,/ /g'); do printf "\n"; fail2ban-client status "$jail" 2>/dev/null; done ;;
                unban) local ip; read -rp "  IP to unban: " ip; [[ -n "$ip" ]] && fail2ban-client unban "$ip" 2>/dev/null && log_success "Unbanned $ip" ;;
                ufw) ufw status verbose 2>/dev/null ;;
            esac
            ;;

        # --- Performance ---
        perf)
            local perf_sub="${2:-}"
            if [[ -z "$perf_sub" ]]; then
                _header "Performance"
                printf "  1) Re-tune (after VPS resize)\n"
                printf "  2) Test TTFB\n"
                printf "  3) FPM status\n"
                printf "  4) OPcache status\n"
                printf "  5) Reload PHP-FPM\n"
                printf "  0) Back\n\n"
                read -rp "  Choose: " perf_sub
                case "$perf_sub" in 1) perf_sub="retune" ;; 2) perf_sub="ttfb" ;; 3) perf_sub="fpm" ;; 4) perf_sub="opcache" ;; 5) perf_sub="reload-fpm" ;; *) return 0 ;; esac
            fi
            case "$perf_sub" in
                retune)
                    detect_hardware; calculate_tune; print_tune_summary
                    confirm "Apply new tuning?" || return 0
                    # Re-render configs
                    configure_nginx; configure_fastcgi_cache; configure_site
                    configure_php_ini; configure_opcache; configure_fpm_pools
                    configure_mariadb; configure_redis
                    systemctl restart nginx "php${PHP_VERSION}-fpm" mariadb redis-server
                    log_success "All configs re-tuned and services restarted."
                    ;;
                ttfb)
                    printf "  Testing TTFB for https://%s ...\n" "$DOMAIN"
                    curl -sk --resolve "${DOMAIN}:443:127.0.0.1" -o /dev/null \
                        -w "  TTFB:  %{time_starttransfer}s\n  Total: %{time_total}s\n" \
                        "https://${DOMAIN}/"
                    ;;
                fpm)
                    printf "\n  ${BOLD}Web pool:${NC}\n"
                    curl -sfk --resolve "${DOMAIN}:443:127.0.0.1" "https://${DOMAIN}/fpm-status" 2>/dev/null | sed 's/^/  /' \
                        || curl -sf http://127.0.0.1/fpm-status 2>/dev/null | sed 's/^/  /' \
                        || printf "  (not accessible)\n"
                    printf "\n  ${BOLD}Workers pool:${NC}\n"
                    curl -sfk --resolve "${DOMAIN}:443:127.0.0.1" "https://${DOMAIN}/fpm-workers-status" 2>/dev/null | sed 's/^/  /' \
                        || curl -sf http://127.0.0.1/fpm-workers-status 2>/dev/null | sed 's/^/  /' \
                        || printf "  (not accessible)\n"
                    ;;
                opcache)
                    _header "OPcache Configuration"
                    local opcache_ini="/etc/php/${PHP_VERSION}/fpm/conf.d/10-opcache-az.ini"
                    if [[ -f "$opcache_ini" ]]; then
                        local oc_enabled oc_mem oc_jit oc_files
                        oc_enabled="$(grep 'opcache.enable ' "$opcache_ini" | cut -d= -f2 | tr -d ' ')"
                        oc_mem="$(grep 'opcache.memory_consumption' "$opcache_ini" | cut -d= -f2 | tr -d ' ')"
                        oc_jit="$(grep 'opcache.jit_buffer_size' "$opcache_ini" | cut -d= -f2 | tr -d ' ')"
                        oc_files="$(grep 'opcache.max_accelerated_files' "$opcache_ini" | cut -d= -f2 | tr -d ' ')"
                        if [[ "$oc_enabled" == "1" ]]; then
                            printf "  Status:       ${GREEN}ENABLED${NC}\n"
                        else
                            printf "  Status:       ${RED}DISABLED${NC}\n"
                        fi
                        printf "  Memory:       %s MB\n" "${oc_mem:-0}"
                        printf "  Max files:    %s\n" "${oc_files:-0}"
                        printf "  JIT buffer:   %s\n" "${oc_jit:-0 (disabled)}"
                        printf "  Revalidate:   %ss\n" "$(grep 'revalidate_freq' "$opcache_ini" | cut -d= -f2 | tr -d ' ')"
                    else
                        printf "  OPcache config not found at %s\n" "$opcache_ini"
                    fi
                    printf "\n  ${DIM}Note: OPcache runs inside PHP-FPM only. CLI has it disabled.${NC}\n"
                    printf "  ${DIM}Reset OPcache: az-wp advanced perf reload-fpm${NC}\n"
                    ;;
                reload-fpm)
                    service_restart "php${PHP_VERSION}-fpm"
                    log_success "PHP-FPM restarted (OPcache cleared)."
                    ;;
            esac
            ;;

        # --- PHP Info ---
        php)
            local php_sub="${2:-}"
            if [[ -z "$php_sub" ]]; then
                _header "PHP ${PHP_VERSION} Info"

                # Version
                local php_ver; php_ver="$(php${PHP_VERSION} -v 2>/dev/null | head -1 | grep -oP 'PHP \K[0-9.]+' || echo '?')"
                printf "  Version:    ${GREEN}PHP %s${NC}\n" "$php_ver"

                # Key config values
                local mem_limit max_exec upload_max
                mem_limit="$(grep 'memory_limit' /etc/php/${PHP_VERSION}/fpm/conf.d/99-az-wp.ini 2>/dev/null | cut -d= -f2 | tr -d ' ' || echo '?')"
                max_exec="$(grep 'max_execution_time' /etc/php/${PHP_VERSION}/fpm/conf.d/99-az-wp.ini 2>/dev/null | cut -d= -f2 | tr -d ' ' || echo '?')"
                upload_max="$(grep 'upload_max_filesize' /etc/php/${PHP_VERSION}/fpm/conf.d/99-az-wp.ini 2>/dev/null | cut -d= -f2 | tr -d ' ' || echo '?')"
                printf "  Memory:     %s\n" "$mem_limit"
                printf "  Max exec:   %ss\n" "$max_exec"
                printf "  Upload max: %s\n" "$upload_max"

                # OPcache
                local oc_mem; oc_mem="$(grep 'memory_consumption' /etc/php/${PHP_VERSION}/fpm/conf.d/10-opcache-az.ini 2>/dev/null | cut -d= -f2 | tr -d ' ' || echo '?')"
                local oc_jit; oc_jit="$(grep 'jit_buffer_size' /etc/php/${PHP_VERSION}/fpm/conf.d/10-opcache-az.ini 2>/dev/null | cut -d= -f2 | tr -d ' ' || echo '0')"
                printf "  OPcache:    %sMB | JIT: %s\n" "$oc_mem" "$oc_jit"

                # FPM pools
                local web_max; web_max="$(grep 'pm.max_children' /etc/php/${PHP_VERSION}/fpm/pool.d/web.conf 2>/dev/null | cut -d= -f2 | tr -d ' ' || echo '?')"
                local wrk_max; wrk_max="$(grep 'pm.max_children' /etc/php/${PHP_VERSION}/fpm/pool.d/workers.conf 2>/dev/null | cut -d= -f2 | tr -d ' ' || echo '?')"
                printf "  FPM:        web=%s | workers=%s\n" "$web_max" "$wrk_max"

                # Extensions
                printf "\n  ${BOLD}Extensions:${NC}\n"
                local ext ext_list
                ext_list="$(php${PHP_VERSION} -m 2>/dev/null | grep -v '^\[' | sort | tr '\n' ' ' || true)"
                local ext_count; ext_count="$(php${PHP_VERSION} -m 2>/dev/null | grep -v '^\[' | grep -v '^$' | wc -l || echo 0)"
                printf "  Total: %s loaded\n\n" "$ext_count"

                # Show key extensions with status
                # Use FPM check for OPcache (CLI has it disabled)
                local key_exts="bcmath curl dom exif fileinfo gd iconv igbinary imagick intl mbstring mysqli pdo_mysql redis soap xml zip"
                for ext in $key_exts; do
                    if php${PHP_VERSION} -m 2>/dev/null | grep -qi "^${ext}$"; then
                        printf "    ${GREEN}%-15s ON${NC}\n" "$ext"
                    else
                        printf "    ${RED}%-15s OFF${NC}\n" "$ext"
                    fi
                done
                # OPcache special check — always ON in FPM if config exists
                if [[ -f "/etc/php/${PHP_VERSION}/fpm/conf.d/10-opcache-az.ini" ]]; then
                    local oc_on; oc_on="$(grep 'opcache.enable ' "/etc/php/${PHP_VERSION}/fpm/conf.d/10-opcache-az.ini" | cut -d= -f2 | tr -d ' ')"
                    if [[ "$oc_on" == "1" ]]; then
                        printf "    ${GREEN}%-15s ON${NC}  ${DIM}(FPM only, CLI disabled by design)${NC}\n" "opcache"
                    else
                        printf "    ${RED}%-15s OFF${NC}\n" "opcache"
                    fi
                else
                    printf "    ${RED}%-15s OFF${NC}  ${DIM}(no config found)${NC}\n" "opcache"
                fi

                printf "\n  1) Install extension\n"
                printf "  2) Show all loaded modules\n"
                printf "  0) Back\n\n"
                read -rp "  Choose: " php_sub
                case "$php_sub" in 1) php_sub="install-ext" ;; 2) php_sub="modules" ;; *) return 0 ;; esac
            fi
            case "$php_sub" in
                install-ext)
                    local ext_name
                    read -rp "  Extension name (e.g. memcached, xdebug): " ext_name
                    [[ -z "$ext_name" ]] && return 0
                    local pkg="php${PHP_VERSION}-${ext_name}"
                    printf "  Installing %s...\n" "$pkg"
                    if NEEDRESTART_MODE=a DEBIAN_FRONTEND=noninteractive apt-get install -y "$pkg" > /dev/null 2>&1; then
                        systemctl restart "php${PHP_VERSION}-fpm"
                        log_success "$pkg installed and FPM restarted."
                    else
                        log_error "Package $pkg not found or install failed."
                        printf "  ${DIM}Search available: apt-cache search php${PHP_VERSION}${NC}\n"
                    fi
                    ;;
                modules)
                    _header "All PHP ${PHP_VERSION} Modules"
                    php${PHP_VERSION} -m 2>/dev/null | grep -v '^\[' | grep -v '^$' | sort | column 2>/dev/null || \
                        php${PHP_VERSION} -m 2>/dev/null | grep -v '^\[' | grep -v '^$' | sort
                    ;;
            esac
            ;;

        # --- Services ---
        services)
            local svc_sub="${2:-}"
            if [[ -z "$svc_sub" ]]; then
                _header "Services Control"
                printf "  1) Restart all\n"
                printf "  2) Restart Nginx\n"
                printf "  3) Restart PHP-FPM\n"
                printf "  4) Restart MariaDB\n"
                printf "  5) Restart Redis\n"
                printf "  0) Back\n\n"
                read -rp "  Choose: " svc_sub
                case "$svc_sub" in 1) svc_sub="all" ;; 2) svc_sub="nginx" ;; 3) svc_sub="fpm" ;; 4) svc_sub="mariadb" ;; 5) svc_sub="redis" ;; *) return 0 ;; esac
            fi
            case "$svc_sub" in
                all) for s in nginx "php${PHP_VERSION}-fpm" mariadb redis-server; do service_restart "$s"; done ;;
                nginx) service_restart nginx ;;
                fpm) service_restart "php${PHP_VERSION}-fpm" ;;
                mariadb) service_restart mariadb ;;
                redis) service_restart redis-server ;;
            esac
            ;;

        # --- Workers ---
        workers)
            local w_sub="${2:-}"
            if [[ -z "$w_sub" ]]; then
                _header "Workers Management"
                local web_active web_max wrk_active wrk_max
                web_active="$(curl -s http://127.0.0.1/fpm-status 2>/dev/null | grep 'active processes:' | head -1 | awk '{print $NF}')" || web_active="?"
                web_max="$(grep 'pm.max_children' /etc/php/${PHP_VERSION}/fpm/pool.d/web.conf 2>/dev/null | awk -F= '{print $2}' | tr -d ' ')" || web_max="?"
                wrk_active="$(curl -s http://127.0.0.1/fpm-workers-status 2>/dev/null | grep 'active processes:' | head -1 | awk '{print $NF}')" || wrk_active="?"
                wrk_max="$(grep 'pm.max_children' /etc/php/${PHP_VERSION}/fpm/pool.d/workers.conf 2>/dev/null | awk -F= '{print $2}' | tr -d ' ')" || wrk_max="?"
                printf "  Web pool:     %s / %s active\n" "$web_active" "$web_max"
                printf "  Workers pool: %s / %s active\n" "$wrk_active" "$wrk_max"
                printf "\n  Long-running (>30s):\n"
                ps -eo pid,etimes,pcpu,pmem,comm 2>/dev/null | grep php-fpm | awk '$2>30 {printf "    PID %-8s %ss  CPU:%s%%  MEM:%s%%\n", $1, $2, $3, $4}' || printf "    (none)\n"
                printf "\n  1) Kill stuck processes (>300s)\n  0) Back\n\n"
                read -rp "  Choose: " w_sub
                case "$w_sub" in 1) w_sub="kill-stuck" ;; *) return 0 ;; esac
            fi
            case "$w_sub" in
                kill-stuck)
                    local pids; pids="$(ps -eo pid,etimes,comm 2>/dev/null | grep php-fpm | awk '$2>300 {print $1}')"
                    if [[ -z "$pids" ]]; then log_info "No stuck processes."; return; fi
                    printf "  Will kill: %s\n" "$pids"
                    confirm "Kill these processes?" || return 0
                    echo "$pids" | xargs kill -9 2>/dev/null || true
                    log_success "Killed stuck processes."
                    ;;
            esac
            ;;

        # --- phpMyAdmin config ---
        pma-config)
            local pma_sub="${2:-}"
            if [[ -z "$pma_sub" ]]; then
                _header "phpMyAdmin Config"
                local pma_path; pma_path="$(state_get PMA_PATH 2>/dev/null)" || pma_path=""
                if [[ -n "$pma_path" && -f /etc/nginx/az-wp-pma.conf ]]; then
                    printf "  Status: ${GREEN}enabled${NC}\n"
                    printf "  URL:    https://%s%s/\n" "$DOMAIN" "$pma_path"
                else
                    printf "  Status: ${RED}disabled${NC}\n"
                fi
                printf "\n  1) Enable\n  2) Disable\n  3) Regenerate URL\n  0) Back\n\n"
                read -rp "  Choose: " pma_sub
                case "$pma_sub" in 1) pma_sub="enable" ;; 2) pma_sub="disable" ;; 3) pma_sub="regenerate" ;; *) return 0 ;; esac
            fi
            case "$pma_sub" in
                enable) _pma_enable ;;
                disable)
                    rm -f /etc/nginx/az-wp-pma.conf /etc/phpmyadmin/conf.d/az-wp-autologin.php /usr/share/phpmyadmin/az-wp-gate.php 2>/dev/null
                    local nginx_conf="/etc/nginx/sites-available/${DOMAIN}.conf"
                    sed -i '/az-wp-pma.conf/d' "$nginx_conf" 2>/dev/null || true
                    service_reload nginx
                    log_success "phpMyAdmin disabled."
                    ;;
                regenerate)
                    rm -f /etc/nginx/az-wp-pma.conf
                    local nginx_conf="/etc/nginx/sites-available/${DOMAIN}.conf"
                    sed -i '/az-wp-pma.conf/d' "$nginx_conf" 2>/dev/null || true
                    _pma_enable
                    ;;
            esac
            ;;

        *) log_warn "Unknown advanced command: $sub" ;;
    esac
}

# ===========================================================================
# phpMyAdmin enable helper
# ===========================================================================
_pma_enable() {
    local nginx_conf="/etc/nginx/sites-available/${DOMAIN}.conf"

    # Install if missing
    if [[ ! -d /usr/share/phpmyadmin ]]; then
        log_info "Installing phpMyAdmin..."
        NEEDRESTART_MODE=a DEBIAN_FRONTEND=noninteractive apt-get install -y phpmyadmin > /dev/null 2>&1 \
            || die "Failed to install phpMyAdmin."
        log_success "phpMyAdmin installed."
    fi

    # Generate base64 URL path (stronger than hex, URL-safe)
    local pma_rand
    pma_rand="$(openssl rand -base64 32 | tr -d '/+=' | cut -c1-24)"
    local pma_path="/db-${pma_rand}"

    # Record expiry (24 hours from now)
    local pma_expiry
    pma_expiry="$(date -d '+24 hours' '+%Y-%m-%d %H:%M:%S' 2>/dev/null || date -v+24H '+%Y-%m-%d %H:%M:%S' 2>/dev/null)"

    # FPM pool
    local pma_pool="/etc/php/${PHP_VERSION}/fpm/pool.d/phpmyadmin.conf"
    if [[ ! -f "$pma_pool" ]]; then
        cat > "$pma_pool" <<FPMPOOL
[phpmyadmin]
user = www-data
group = www-data
listen = /run/php/php${PHP_VERSION}-fpm-pma.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0660
pm = ondemand
pm.max_children = 2
pm.process_idle_timeout = 60s
request_terminate_timeout = 300
php_admin_value[open_basedir] = /usr/share/phpmyadmin:/tmp:/var/lib/phpmyadmin:/etc/phpmyadmin:/usr/share/php
php_admin_value[upload_max_filesize] = 256M
php_admin_value[post_max_size] = 256M
php_admin_value[max_execution_time] = 300
FPMPOOL
        systemctl restart "php${PHP_VERSION}-fpm"
    fi

    # Nginx snippet
    cat > /etc/nginx/az-wp-pma.conf <<PMACONF
    # phpMyAdmin — managed by az-wp (expires: ${pma_expiry})
    location ^~ ${pma_path}/ {
        alias /usr/share/phpmyadmin/;
        index index.php;
        location ~ \.php\$ {
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME \$request_filename;
            fastcgi_pass unix:/run/php/php${PHP_VERSION}-fpm-pma.sock;
        }
    }
    # end phpMyAdmin
PMACONF

    sed -i '/az-wp-pma.conf/d' "$nginx_conf" 2>/dev/null || true
    if ! grep -q "az-wp-pma.conf" "$nginx_conf"; then
        sed -i '/^}$/i \    include /etc/nginx/az-wp-pma.conf;' "$nginx_conf"
    fi

    # Auto-login config
    mkdir -p /etc/phpmyadmin/conf.d
    local db_user db_pass
    db_user="$(state_get DB_USER)" || db_user=""
    db_pass="$(state_get DB_PASS)" || db_pass=""
    cat > /etc/phpmyadmin/conf.d/az-wp-autologin.php <<PHPCFG
<?php
\$cfg['Servers'][1]['auth_type'] = 'config';
\$cfg['Servers'][1]['user'] = '${db_user}';
\$cfg['Servers'][1]['password'] = '${db_pass}';
\$cfg['Servers'][1]['AllowNoPassword'] = false;
PHPCFG

    # Setup auto-disable cron (24h)
    local disable_at
    disable_at="$(date -d '+24 hours' '+%M %H %d %m *' 2>/dev/null || date -v+24H '+%M %H %d %m *' 2>/dev/null)"
    cat > /etc/cron.d/az-wp-pma-expire <<CRONCFG
# az-wp: auto-disable phpMyAdmin after 24h
${disable_at} root /usr/local/bin/az-wp advanced pma-config disable > /dev/null 2>&1 && rm -f /etc/cron.d/az-wp-pma-expire
CRONCFG
    chmod 644 /etc/cron.d/az-wp-pma-expire

    if nginx -t 2>/dev/null; then
        service_reload nginx
    else
        log_error "Nginx config test failed."
        rm -f /etc/nginx/az-wp-pma.conf
        sed -i '/az-wp-pma.conf/d' "$nginx_conf"
        return 1
    fi

    state_set "PMA_PATH" "$pma_path"
    state_set "PMA_EXPIRY" "$pma_expiry"
    log_success "phpMyAdmin enabled (auto-disables in 24h)."
    printf "\n  ${BOLD}URL:${NC} https://%s%s/\n" "$DOMAIN" "$pma_path"
    printf "  ${DIM}Expires: %s${NC}\n\n" "$pma_expiry"
}

# ===========================================================================
# 9) HELP
# ===========================================================================
menu_help() {
    printf "\n  ${BOLD}az-wp${NC} v%s\n" "$AZ_VERSION"
    printf "  WordPress management CLI for single-site VPS.\n\n"
    show_usage
}

# ===========================================================================
# MAIN DISPATCHER
# ===========================================================================
main() {
    load_state

    if [[ $# -gt 0 ]]; then
        case "$1" in
            status)   menu_status ;;
            wp)       menu_wordpress "${2:-}" ;;
            db)       menu_database "${2:-}" "${3:-}" ;;
            cache)    menu_cache "${2:-}" ;;
            backup)   menu_backup "${2:-}" "${3:-}" ;;
            cron)     menu_cron "${2:-}" "${3:-}" ;;
            domain)   menu_domain "${2:-}" ;;
            advanced) menu_advanced "${2:-}" "${3:-}" ;;
            help|-h|--help) menu_help ;;
            # Shortcuts
            login)    _wp_auto_login ;;
            pma)      menu_database pma ;;
            retune)   menu_advanced perf retune ;;
            ssl)      menu_advanced ssl "${2:-}" ;;
            *)        printf "Unknown: %s\n" "$1"; show_usage ;;
        esac
    else
        while true; do
            show_menu
            printf "\n"
            read -rp "  Choose [0-9]: " choice
            case "$choice" in
                1) menu_status ;;
                2) menu_wordpress ;;
                3) menu_database ;;
                4) menu_cache ;;
                5) menu_backup ;;
                6) menu_cron ;;
                7) menu_domain ;;
                8) menu_advanced ;;
                9) menu_help ;;
                0) printf "  Goodbye!\n"; exit 0 ;;
                *) ;;
            esac
        done
    fi
}

main "$@"
