; az-wp custom PHP settings
; Generated by az-wp-single installer

[PHP]
memory_limit = ${TUNE_PHP_MEMORY_LIMIT}
max_execution_time = 300
max_input_time = 300
max_input_vars = 5000
upload_max_filesize = 256M
post_max_size = 256M
max_file_uploads = 50

display_errors = Off
display_startup_errors = Off
log_errors = On
error_log = /var/log/php/error.log
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT

expose_php = Off
allow_url_fopen = On
allow_url_include = Off
cgi.fix_pathinfo = 0

; Session security
session.cookie_httponly = 1
session.cookie_secure = 1
session.cookie_samesite = Lax
session.use_strict_mode = 1
session.gc_maxlifetime = 1440

; Realpath cache
realpath_cache_size = 4096K
realpath_cache_ttl = 600

; Security - FPM only (CLI not affected)
; Note: exec is allowed because AffiliateCMS CachePreload needs it
; for cache management (ps, find, nginx-cache-purge)
disable_functions = passthru,shell_exec,system,proc_open,popen
open_basedir = ${WEB_ROOT}:/tmp:/usr/share/php:/run/redis
